.idea/discord.xml, .idea/git_toolbox_prj.xml, .idea/gradle.xml, .idea/misc.xml, app/build.gradle.kts, app/src/main/java/com/example/bellyfull/sampleDBCode.java, build.gradle.kts, google-services.json
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
Added files, dependencies and build.gradle plugin lines needed for Firebase integration and connection with the app.
=> Firebase integration

app/src/main/java/com/example/bellyfull/modules/PregnancyTracking/Adapter/Test.java, app/src/main/java/com/example/bellyfull/modules/PregnancyTracking/Fragments/test.java
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
Add another folders
=> Add PregnancyTracking

app/build.gradle.kts
<table>
<tr>
<td>
Urgency
</td>
<td>
🔴 **Very urgent, blocking other work**
</td>
</tr>
</table>
=> resolve repeating dependency error

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/example/bellyfull/Constant/db_constant.java, app/src/main/java/com/example/bellyfull/Constant/preference_constant.java, app/src/main/java/com/example/bellyfull/PreLoginActivity.java, app/src/main/java/com/example/bellyfull/data/firebase/ports/dbLoginCallback.java, app/src/main/java/com/example/bellyfull/data/firebase/ports/fbLoginRepository.java, app/src/main/java/com/example/bellyfull/data/firebase/repository/fbLoginRepositoryImpl.java, app/src/main/java/com/example/bellyfull/data/firebase/repository/fbSignUpRepositoryImpl.java, app/src/main/java/com/example/bellyfull/modules/Authentication/Fragments/LoginFragment.java, app/src/main/java/com/example/bellyfull/utils/AuthenticationUtils.java
<table>
<tr>
<td>
Urgency
</td>
<td>
🔴 **Very urgent, blocking other work**
</td>
</tr>
</table>
=> done authentication backend

app/src/main/java/com/example/bellyfull/modules/AdviceAndTips/Adapter/AdviceAdapter.java, app/src/main/java/com/example/bellyfull/modules/AdviceAndTips/Fragments/AdviceTipsFragment.java, app/src/main/java/com/example/bellyfull/modules/AdviceAndTips/Models/AdviceItem.java, app/src/main/res/drawable/events_bloc.xml, app/src/main/res/drawable/vector.xml, app/src/main/res/layout/fragment_advice_tips.xml, app/src/main/res/layout/item_advice.xml, app/src/main/res/layout/item_events_bloc.xml, app/src/main/res/layout/item_vector.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
=> Fix mistake: Accidentally deleted original strings.xml content just now

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/bellyfull/EmergencyWidget.java, app/src/main/java/com/example/bellyfull/modules/EmergencyAndHelp/Fragments/EmergencyActivity.java, app/src/main/java/com/example/bellyfull/modules/EmergencyAndHelp/Fragments/NearbySearchAsyncTask.java, app/src/main/java/com/example/bellyfull/modules/EmergencyAndHelp/Fragments/PlaceResult.java, app/src/main/res/layout/emergency_location.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
Further funcionality for emergency - managed to get current location, and markers for hospitals in 5km radius.
TODO: try to get the most important phone number
TODO: make it not look so ugly
=> done for the day

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/bellyfull/modules/EmergencyAndHelp/Fragments/EmergencyActivity.java, app/src/main/java/com/example/bellyfull/modules/EmergencyAndHelp/Fragments/EmergencyWidget.java, app/src/main/java/com/example/bellyfull/modules/EmergencyAndHelp/Fragments/MedicalInfoActivity.java, app/src/main/java/com/example/bellyfull/modules/EmergencyAndHelp/Fragments/NearbySearchAsyncTask.java, app/src/main/res/drawable/map_bg_box.xml, app/src/main/res/layout/emergency_location.xml, app/src/main/res/layout/emergency_widget.xml, app/src/main/res/layout/medical_info.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
Added page for viewing victim's medical information
TODO: Get actual data
TODO: Beautify UI
Made several changes to map page UI
- added button to link to medical info
- tried to do rounded edges for the map, mcm not so effective
TODO: add border for TextView
Search logic improved
- removed results of individual doctors in hospitals
Updated widget
- added immutable flag so it works as intended
Updated manifest
- added MedicalInfoActivity
=> abit of beautification and work on displaying medical info

app/src/main/java/com/example/bellyfull/modules/General/ProfileFragment.java, app/src/main/java/com/example/bellyfull/utils/AlertDialogUtil.java, app/src/main/res/navigation/main_nav_graph.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
Finished logout impl
=> finish logout impl

app/src/main/java/com/example/bellyfull/MainActivity.java, app/src/main/res/values-v21/styles.xml, app/src/main/res/values/themes.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
change the color of status bar
=> change status bar color

app/src/main/java/com/example/bellyfull/Constant/db_collection_constant.java, app/src/main/java/com/example/bellyfull/data/firebase/collection/User.java, app/src/main/java/com/example/bellyfull/data/firebase/ports/dbProfileCallback.java, app/src/main/java/com/example/bellyfull/data/firebase/ports/dbProfileRepository.java, app/src/main/java/com/example/bellyfull/data/firebase/repository/fbLoginRepositoryImpl.java, app/src/main/java/com/example/bellyfull/data/firebase/repository/fbProfileRepositoryImpl.java, app/src/main/java/com/example/bellyfull/data/firebase/repository/fbSignUpRepositoryImpl.java, app/src/main/java/com/example/bellyfull/modules/General/ProfileFragment.java, app/src/main/res/layout/fragment_edit_profile.xml, app/src/main/res/layout/fragment_profile.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
Added database impl for profile
=> done database impl for user getter

app/src/main/java/com/example/bellyfull/data/firebase/ports/dbProfileRepository.java, app/src/main/java/com/example/bellyfull/data/firebase/repository/fbProfileRepositoryImpl.java, app/src/main/java/com/example/bellyfull/modules/General/ProfileEditFragment.java, app/src/main/res/layout/fragment_edit_profile.xml, app/src/main/res/navigation/main_nav_graph.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
Done be edit profile
=> done edit profile MVP

app/src/main/java/com/example/bellyfull/data/firebase/repository/eventRepositoryImpl.java
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
fix naming
=> fix naming calendar

app/src/main/java/com/example/bellyfull/MainActivity.java, app/src/main/java/com/example/bellyfull/modules/visualisation/Fragments/BabyVisualisationFragment.java, app/src/main/java/com/example/bellyfull/modules/visualisation/Fragments/MomVisualisationFragment.java, app/src/main/res/layout/fragment_baby_visualisation.xml, app/src/main/res/layout/fragment_mom_visualisation.xml, app/src/main/res/menu/bottom_nav_menu.xml, app/src/main/res/navigation/main_nav_graph.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
add visual placeholder for visualisation module
=> add visual placeholder for visualisation module

app/src/main/java/com/example/bellyfull/Constant/db_collection_constant.java, app/src/main/java/com/example/bellyfull/Constant/preference_constant.java, app/src/main/java/com/example/bellyfull/MainActivity.java, app/src/main/java/com/example/bellyfull/data/firebase/collection/BabyInfo.java, app/src/main/java/com/example/bellyfull/data/firebase/ports/dbBabyInfoCallback.java, app/src/main/java/com/example/bellyfull/data/firebase/ports/dbBabyInfoRepository.java, app/src/main/java/com/example/bellyfull/data/firebase/repository/fbBabyInfoRepositoryImpl.java, app/src/main/java/com/example/bellyfull/data/firebase/repository/fbProfileRepositoryImpl.java, app/src/main/java/com/example/bellyfull/modules/HomeFragment.java, app/src/main/java/com/example/bellyfull/modules/PregnancyTracking/Fragments/BabyInputFragment.java, app/src/main/res/layout/fragment_baby_input.xml, app/src/main/res/navigation/main_nav_graph.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
implemented baby input functionality
=> done baby input impl

app/src/main/java/com/example/bellyfull/data/firebase/collection/BabyInfo.java, app/src/main/java/com/example/bellyfull/data/firebase/ports/dbBabyInfoCallback.java, app/src/main/java/com/example/bellyfull/data/firebase/ports/dbBabyInfoRepository.java, app/src/main/java/com/example/bellyfull/data/firebase/repository/fbBabyInfoRepositoryImpl.java, app/src/main/java/com/example/bellyfull/modules/PregnancyTracking/Fragments/BabyInputFragment.java, app/src/main/res/layout/fragment_baby_input.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
change baby input impl
=> change impl for baby input

app/src/main/java/com/example/bellyfull/data/firebase/collection/HealthData.java, app/src/main/res/layout/fragment_mom_input.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
done fe mom input
=> done fe mom input

app/build.gradle.kts, app/google-services.json, app/src/main/java/com/example/bellyfull/data/firebase/repository/fbEmergencyImpl.java, app/src/main/java/com/example/bellyfull/modules/Authentication/Fragments/LoginFragment.java, app/src/main/res/values/strings.xml, build.gradle.kts
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
- implemented Google Login
- Upgraded Gradle to 8.2.1
=> Google Authentication

app/src/main/java/com/example/bellyfull/MainActivity.java, app/src/main/java/com/example/bellyfull/modules/PregnancyTracking/Fragments/MomInputFragment.java, app/src/main/res/navigation/main_nav_graph.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
Fix back button not popping off fragment
=> fix back button not pop fragment

app/src/main/java/com/example/bellyfull/modules/Authentication/Fragments/LoginFragment.java, app/src/main/java/com/example/bellyfull/modules/Authentication/Fragments/RegisterFragment.java, app/src/main/res/layout/fragment_register.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
added google sign in from loginfragment to registerfragment
reordered the imports
=> Google Sign-Up in RegisterFragment

.idea/compiler.xml, .idea/gradle.xml, .idea/misc.xml, app/src/main/java/com/example/bellyfull/modules/AdviceAndTips/Adapter/AdviceAdapter.java, app/src/main/java/com/example/bellyfull/modules/AdviceAndTips/Fragments/AdviceAndTipsFragment.java, app/src/main/java/com/example/bellyfull/modules/AdviceAndTips/Fragments/AdviceTipsFragment.java, app/src/main/java/com/example/bellyfull/modules/AdviceAndTips/Models/AdviceItem.java, app/src/main/res/layout/fragment_advice_and_tips.xml, app/src/main/res/layout/fragment_advice_tips.xml, app/src/main/res/layout/fragment_profile.xml, build.gradle.kts
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
=> Create TipsFragment (do the xml and update the original backend code in advice and tips module)

app/src/main/java/com/example/bellyfull/Constant/preference_constant.java, app/src/main/java/com/example/bellyfull/modules/Authentication/Fragments/RegisterFragment.java, app/src/main/res/values/strings.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
fix register breaking
=> fix register breaking

app/src/main/res/layout/fragment_baby_input.xml, app/src/main/res/layout/fragment_mom_input.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
minor feature fix
=> minor fix to let user enter in baby info manually

.idea/deploymentTargetDropDown.xml, .idea/gradle.xml, app/src/main/java/com/example/bellyfull/data/firebase/collection/Event.java, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/Fragments/CalendarFragment.java, app/src/main/res/layout/dialog_event_input.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
add category function but in a stupid way :)
=> Add category

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/example/bellyfull/modules/PregnancyTracking/Fragments/BabyInputFragment.java, app/src/main/java/com/example/bellyfull/modules/PregnancyTracking/Fragments/MomInputFragment.java, app/src/main/java/com/example/bellyfull/utils/hideKeyboardUtils.java
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
fix baby input breaking and add keyboard dismiss feature
=> fix baby input breaking and add keyboard dismiss

app/src/main/java/com/example/bellyfull/Constant/db_collection_constant.java, app/src/main/java/com/example/bellyfull/MainActivity.java, app/src/main/java/com/example/bellyfull/data/firebase/collection/MomInfo.java, app/src/main/java/com/example/bellyfull/data/firebase/ports/dbMomInfoRepository.java, app/src/main/java/com/example/bellyfull/data/firebase/repository/dbMomInfoRepositoryImpl.java, app/src/main/java/com/example/bellyfull/modules/General/InputDialog.java, app/src/main/java/com/example/bellyfull/modules/PregnancyTracking/Fragments/BabyInputFragment.java, app/src/main/java/com/example/bellyfull/modules/PregnancyTracking/Fragments/MomInputFragment.java, app/src/main/res/layout/fragment_mom_input.xml, app/src/main/res/layout/layout_dialog.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
done mom module, to do some better UI in the future
=> done mom input module

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/Fragments/BlankFragment.java, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/Fragments/CalendarFragment.java, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/Fragments/EventInputFragment.java, app/src/main/res/drawable/rounded_corner.xml, app/src/main/res/layout/dialog_event_input.xml, app/src/main/res/layout/fragment_blank.xml, app/src/main/res/layout/fragment_calendar.xml, app/src/main/res/layout/fragment_event_input.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
Changed Calendar Event Input from dialog to Fragment style
=> Changed Calendar Event Input from dialog to Fragment style

app/src/main/java/com/example/bellyfull/PreLoginActivity.java, app/src/main/java/com/example/bellyfull/data/firebase/collection/User.java, app/src/main/java/com/example/bellyfull/data/firebase/ports/dbBabyInfoRepository.java, app/src/main/java/com/example/bellyfull/data/firebase/ports/dbEmergency.java, app/src/main/java/com/example/bellyfull/data/firebase/ports/dbProfileRepository.java, app/src/main/java/com/example/bellyfull/data/firebase/repository/dbMomInfoRepositoryImpl.java, app/src/main/java/com/example/bellyfull/data/firebase/repository/eventRepositoryImpl.java, app/src/main/java/com/example/bellyfull/data/firebase/repository/fbEmergencyImpl.java, app/src/main/java/com/example/bellyfull/data/firebase/repository/fbLoginRepositoryImpl.java, app/src/main/java/com/example/bellyfull/data/firebase/repository/fbSignUpRepositoryImpl.java, app/src/main/java/com/example/bellyfull/modules/AdviceAndTips/Fragments/AdviceAndTipsFragment.java, app/src/main/java/com/example/bellyfull/modules/Authentication/Fragments/EmailSender.java, app/src/main/java/com/example/bellyfull/modules/Authentication/Fragments/ForgotPwdFragment.java, app/src/main/java/com/example/bellyfull/modules/Authentication/Fragments/LoginFragment.java, app/src/main/java/com/example/bellyfull/modules/Authentication/Fragments/RegisterFragment.java, app/src/main/java/com/example/bellyfull/modules/Authentication/Fragments/ResetPasswordFragment.java, app/src/main/java/com/example/bellyfull/modules/EmergencyAndHelp/Fragments/EmergencyActivity.java, app/src/main/java/com/example/bellyfull/modules/EmergencyAndHelp/Fragments/EmergencyWidget.java, app/src/main/java/com/example/bellyfull/modules/General/InputDialog.java, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/Fragments/BlankFragment.java, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/Fragments/CalendarFragment.java, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/Fragments/EventInputFragment.java, app/src/main/java/com/example/bellyfull/modules/PregnancyTracking/Fragments/MomInputFragment.java, app/src/main/java/com/example/bellyfull/modules/visualisation/Fragments/Baby.java, app/src/main/java/com/example/bellyfull/modules/visualisation/Fragments/BabyVisualisationFragment.java, app/src/main/java/com/example/bellyfull/modules/visualisation/Fragments/MyAdapter.java, app/src/main/java/com/example/bellyfull/modules/visualisation/Fragments/WHOgraphicFragment.java, app/src/main/java/com/example/bellyfull/utils/TextValidator.java
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
cleanup
=> removed unused imports throughout the project

app/src/main/java/com/example/bellyfull/modules/visualisation/Fragments/BabyVisualisationFragment.java, app/src/main/res/layout/fragment_baby_visualisation.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
Added button to update baby. Close case for baby visualisation first.
=> baby visualisation frontend

app/src/main/java/com/example/bellyfull/modules/Authentication/Fragments/RegisterFragment.java, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/InputBottomSheet.java, app/src/main/java/com/example/bellyfull/utils/showColorPickerUtil.java, app/src/main/res/layout/dialog_event_category.xml, app/src/main/res/values/colors.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
done mvp for event category
=> done MVP for event category

app/src/main/java/com/example/bellyfull/data/firebase/collection/Event.java, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/InputBottomSheet.java, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/ReminderBroadcastReceiver.java, app/src/main/res/layout/bottom_sheet_layout.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
chore work on calendar event
=> chore work on event calendar

app/src/main/java/com/example/bellyfull/modules/EmergencyAndHelp/Fragments/NearbySearchAsyncTask.java, app/src/main/res/layout/fragment_mom_visualisation.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
fix breaking ampersand
=> fix breaking ampersand

app/src/main/java/com/example/bellyfull/data/firebase/ports/eventRepository.java, app/src/main/java/com/example/bellyfull/data/firebase/repository/eventRepositoryImpl.java, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/InputBottomSheet.java
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
add event be integration
=> add event be integration

app/src/main/AndroidManifest.xml, app/src/main/java/com/example/bellyfull/Constant/notification_constant.java, app/src/main/java/com/example/bellyfull/MainActivity.java, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/Fragments/CalendarFragment.java, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/InputBottomSheet.java, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/NotificationReceiver.java
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
event notification done
=> notification event

app/src/main/java/com/example/bellyfull/data/firebase/collection/Event.java, app/src/main/java/com/example/bellyfull/data/firebase/repository/eventRepositoryImpl.java, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/Fragments/CalendarFragment.java, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/InputBottomSheet.java
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
done FE calendar
=> done FE calendar

app/src/main/java/com/example/bellyfull/modules/HomeFragment.java, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/Fragments/CalendarFragment.java, app/src/main/res/layout/event_item.xml, app/src/main/res/layout/fragment_home.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
done event visualisation for home page
=> done home event visualisation

app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/InputBottomSheet.java, app/src/main/res/layout/bottom_sheet_layout.xml, app/src/main/res/layout/fragment_home.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
change clickable to whole input
=> change clickable to whole input

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/example/bellyfull/modules/HomeFragment.java, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/Fragments/CalendarFragment.java
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
fix event visualisation showing everyone's schedule
=> fix event visualisation showing everyone's schedule

app/src/main/java/com/example/bellyfull/modules/Authentication/Fragments/EmailSender.java, app/src/main/java/com/example/bellyfull/modules/EmergencyAndHelp/Fragments/EmergencyActivity.java, app/src/main/java/com/example/bellyfull/modules/HomeFragment.java, app/src/main/java/com/example/bellyfull/utils/WeekCalculator.java, app/src/main/res/layout/fragment_home.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
done pregnancy weeks implementation
=> done pregnancy weeks implementation

.idea/.name, .idea/deploymentTargetDropDown.xml, app/src/main/java/com/example/bellyfull/data/firebase/collection/BabyInfo.java, app/src/main/java/com/example/bellyfull/modules/EmergencyAndHelp/Fragments/EmergencyActivity.java, app/src/main/java/com/example/bellyfull/modules/PregnancyTracking/Fragments/BabyInputFragment.java, app/src/main/java/com/example/bellyfull/modules/PregnancyTracking/Fragments/MomInputFragment.java, app/src/main/res/layout/fragment_baby_input.xml, app/src/main/res/layout/fragment_mom_input.xml, app/src/main/res/layout/fragment_profile.xml, app/src/main/res/navigation/main_nav_graph.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
Removed JPEG textview in mom info and baby info
Completed database getters
Add toast for email sending
Slight layout changes to suit my phone better for profile edit
=> misc changes

app/src/main/java/com/example/bellyfull/modules/EmergencyAndHelp/Fragments/EmergencyActivity.java
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
replace to make toast message send to correct email
=> replace correct email

app/src/main/java/com/example/bellyfull/data/firebase/ports/eventRepository.java, app/src/main/java/com/example/bellyfull/data/firebase/repository/eventRepositoryImpl.java, app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/InputBottomSheet.java, app/src/main/res/layout/bottom_sheet_layout.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
integration with phone calendar
=> done integration with calendar

app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/InputBottomSheet.java
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
use constants instead of hard coded strings for calendar contract
=> use constants instead of hard coded strings

.idea/deploymentTargetDropDown.xml, app/src/main/java/com/example/bellyfull/utils/showColorPickerUtil.java, app/src/main/res/layout/bottom_sheet_layout.xml, app/src/main/res/layout/dialog_event_category.xml, app/src/main/res/layout/fragment_home.xml, app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml, app/src/main/res/values/colors.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
add some colours in add category
=> add some colours in add category

app/src/main/java/com/example/bellyfull/modules/PersonalisedNotifications/NotificationReceiver.java, app/src/main/res/layout/fragment_mom_visualisation.xml
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
refactor mom visualisation ui
=> refactor mom visualisation ui

app/src/main/java/com/example/bellyfull/modules/HomeFragment.java
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
fix null pointer exception on home page
=> fix null pointer exception on home page

README.md
<table>
<tr>
<td>
Urgency
</td>
<td>
</td>
</tr>
</table>
Generate readme file
=> generate readme
